### ISSUE TITLE
add nano functions example?

### ISSUE THREAD

**Issue by kmarquardsen** [yunspace/serverless-golang#19]
Is this possible/would it provide value? 

```
functions:
  create:
    handler: todos/handler.Handler
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: todos/handler.Handler
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: todos/handler.Handler
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: todos/handler.Handler
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: todos/handler.Handler
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
```
